# Generated by Django 3.2.7 on 2021-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название игры')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('company', models.ManyToManyField(related_name='games', to='companies.Company')),
                ('genres', models.ManyToManyField(related_name='games', to='films.Genre')),
            ],
        ),
    ]
