# Generated by Django 3.2.7 on 2021-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('films', '0002_auto_20211205_0919'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='games', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='games', to='films.Genre'),
        ),
    ]
