# Generated by Django 3.2.7 on 2021-12-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0002_user_is_manager'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', to='users.Actor'),
        ),
        migrations.AlterField(
            model_name='film',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='films', to='users.director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', to='films.Genre'),
        ),
    ]
