# Generated by Django 3.2.7 on 2021-11-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(verbose_name='Текст комментария')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сообщества')),
                ('description', models.TextField(verbose_name='Описание сообщества')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование подписки')),
                ('duration', models.DurationField(verbose_name='Срок подписки')),
            ],
        ),
        migrations.CreateModel(
            name='UserFilmStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.TimeField(verbose_name='Затраченное время')),
            ],
        ),
        migrations.CreateModel(
            name='UserGameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.TimeField(verbose_name='Затраченное время')),
            ],
        ),
        migrations.CreateModel(
            name='UserSeriesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.TimeField(verbose_name='Затраченное время')),
                ('genres', models.ManyToManyField(related_name='series_statistics', to='films.Genre')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_statistics', to='series.series')),
            ],
        ),
    ]
