# Generated by Django 3.2.7 on 2021-12-12 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_auto_20211205_0959'),
        ('films', '0004_alter_genre_name'),
        ('games', '0003_auto_20211205_0959'),
        ('series', '0007_alter_series_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeriesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.TimeField(verbose_name='Затраченное время')),
                ('genres', models.ManyToManyField(blank=True, related_name='series_statistics', to='films.Genre')),
                ('series', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_statistics', to='series.series')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series_statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.TimeField(verbose_name='Затраченное время')),
                ('games', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_statistics', to='games.game')),
                ('genres', models.ManyToManyField(blank=True, related_name='game_statistics', to='films.Genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFilmStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.TimeField(verbose_name='Затраченное время')),
                ('films', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='film_statistics', to='films.film')),
                ('genres', models.ManyToManyField(blank=True, related_name='film_statistics', to='films.Genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='film_statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование подписки')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Срок подписки')),
                ('services', models.ManyToManyField(blank=True, related_name='subscriptions', to='services.Service')),
                ('users', models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сообщества')),
                ('description', models.TextField(verbose_name='Описание сообщества')),
                ('users', models.ManyToManyField(related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(verbose_name='Текст комментария')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
