# Generated by Django 3.2.7 on 2021-12-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
