# Generated by Django 3.2.7 on 2021-11-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('companies', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название сериала')),
                ('series_number', models.IntegerField(verbose_name='Количество серий')),
                ('actors', models.ManyToManyField(related_name='series', to='users.Actor')),
                ('company', models.ManyToManyField(related_name='series', to='companies.Company')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='series', to='users.director')),
                ('genres', models.ManyToManyField(related_name='series', to='films.Genre')),
            ],
        ),
    ]
