# Generated by Django 3.2.7 on 2021-12-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20211205_0959'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='series', to='films.Genre'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_number',
            field=models.IntegerField(null=True, verbose_name='Количество серий'),
        ),
    ]
