# Generated by Django 3.2.7 on 2021-12-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20211211_1708'),
        ('series', '0002_auto_20211212_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='series', to='companies.Company'),
        ),
    ]
