# Generated by Django 3.2.7 on 2021-12-12 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211210_0752'),
        ('series', '0003_alter_series_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='series', to='users.director'),
        ),
    ]
