# Generated by Django 3.2.7 on 2021-12-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211210_0752'),
        ('series', '0004_alter_series_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='series', to='users.Actor'),
        ),
    ]
