# Generated by Django 3.2.7 on 2021-11-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('films', '0001_initial'),
        ('games', '0001_initial'),
        ('services', '0002_auto_20211128_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='films',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='films.Film'),
        ),
        migrations.AlterField(
            model_name='service',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='service',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='series.Series'),
        ),
    ]
